##########################
#                        #
#        DeathBan        #
#                        #
##########################

# This plugin is sooo easy to use!
# You need only paste your command below!

# Yeah thats right
# paste command down below

# ↓ Here paste it! ↓

command: "ban {PLAYER}" # ← Soo replace it!

# ↑ JUST PASTE IT! ↑

message: "WoW! you survive this :O"

# If you want bypass that command you need premission: deathban.bypass
