##########################
#        DeathBan        #ˑ
#  created by BoyBACKS   #ˑ
##########################

# This plugin is sooo easy to use!ˑ
# You need only paste your command below!ˑ

# Yeah thats rightˑ
# paste command down belowˑ

# ↓ Here paste it! ↓ˑ

command: "ban {PLAYER}" # ← Soo replace it!ˑ

# ↑ JUST PASTE IT! ↑ˑ

# Time counted in 'ticks' to execute the command (20 ticks = 1s)
# !!! Values less than 5 may result from item cloning !!!
time: 5

# Message that displays after death with 'deathban.bypass' permissions
message: "WoW! You survived this :O"

